
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
       VERSION: "2025"
       DISK_SIZE: "700G"
       MANUAL: "Y"
       RAM_SIZE: "20G"
       DISK2_SIZE: "200G"
       DISK3_SIZE: "299G"
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/sdb:/disk1
      - /dev/sdc1:/disk2 
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
      - ./disk2:/storage2
      - ./disk3:/storage3  
    restart: always
    stop_grace_period: 2m
