services:
  windows:
    build: .
    container_name: windows 
    devices:
      - /dev/kvm
      - /dev/dri:/dev/dri
    cap_add:
      - NET_ADMIN
    environment:
      - GPU: "yes"
      - VGA: "virtio-gpu-gl-pci"
    ports:
      - 8006:8006
    volumes:  
      - ./windows:/storage
    restart: on-failure
