services:
  windows:
    container_name: windows
    image: ghcr.io/dockur/windows
    environment:
      RAM_SIZE: "90GB "
      DISK_SIZE: "2TB"
      CPU_CORES: "100"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: on-failure
    stop_grace_period: 2m
